# Generated by Django 5.1.1 on 2024-09-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="menus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="users.menu",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission",
                to="users.permission",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[(1, "admin"), (2, "editor"), (3, "gust")], max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="permissions", to="users.permission"
            ),
        ),
    ]
