# Generated by Django 3.0 on 2024-02-14 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '单板类别',
                'verbose_name_plural': '单板类别',
                'db_table': 'device_category',
            },
        ),
        migrations.CreateModel(
            name='Pdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('pdu_category', models.CharField(max_length=50, verbose_name='pdu类型')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='连接地址')),
            ],
            options={
                'verbose_name': 'pdu',
                'verbose_name_plural': 'pdu',
                'db_table': 'pdu_detail',
            },
        ),
        migrations.CreateModel(
            name='ShareHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='连接地址')),
            ],
            options={
                'verbose_name': '串口服务器',
                'verbose_name_plural': '串口服务器',
                'db_table': 'sharehost_detail',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('ip_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='连接地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(max_length=50, verbose_name='登录用户')),
                ('password', models.CharField(max_length=50, verbose_name='登录密码')),
                ('pdu_port', models.IntegerField(default=0, verbose_name='端口')),
                ('sharehost_port', models.IntegerField(default=0, verbose_name='端口')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dc', to='device.Device', verbose_name='单板类别')),
                ('pdu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pc', to='device.Pdu', verbose_name='pdu')),
                ('share_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sc', to='device.ShareHost', verbose_name='share_host')),
            ],
            options={
                'verbose_name': '单板信息',
                'verbose_name_plural': '单板信息',
                'db_table': 'device',
            },
        ),
    ]
