"""
Django settings for uric_api project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .base import *

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": "127.0.0.1",
        "PORT": 3306,
        "USER": "root",
        "PASSWORD": "root",
        "NAME": "uric",
    }
}

ALLOWED_HOSTS = ["127.0.0.1:8000","localhost","localhost:8080" ]

# CORS组的配置信息
CORS_ORIGIN_WHITELIST = (
    # 'www.uric.cn:8080', # 如果这样写不行的话，就加上协议(http://www.uric.cn:8080，因为不同的corsheaders版本可能有不同的要求)
    'http://127.0.0.1:8000',
    'http://localhost:9528',
    'https://localhost:9528',
)
CORS_ALLOW_HEADERS = [
    'token',  # 添加你的自定义请求头
    'content-type',  # 添加你的自定义请求头
    # 其他允许的请求头
]

JENKINS = {
    "server_url": 'http://192.168.101.8:8888/',
    "username": 'admin',
    "password": '11217915472cb72a7edb9a4de8113a5928',
}
GITLAB = {
    "url": "http://192.168.101.8:8993/",
    "token": "LAgbKLyaysE4UjPyX1EV",
}


#  ############################# Django发邮件 #############################
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True  # 是否使用TLS安全传输协议(用于在两个通信应用程序之间提供保密性和数据完整性。)
EMAIL_USE_SSL = False  # 是否使用SSL加密，qq企业邮箱要求使用
EMAIL_HOST = 'smtp.qq.com'  # 发送邮件的邮箱 的 SMTP服务器，这里用了163邮箱
EMAIL_PORT = 25  # 发件箱的SMTP服务器端口
EMAIL_HOST_USER = '2521532473@qq.com'  # 发送邮件的邮箱地址
EMAIL_HOST_PASSWORD = 'hlxqpyuxyvntdjef'  # 发送邮件的邮箱密码(这里使用的是授权码)
EMAIL_TO_USER_LIST = ['zhougang@zjaxtynkjyxgs128.wecom.work']   # 此字段是可选的，用来配置收件人列表
MONITOR_SCRIPT = BASE_DIR.parent / "scripts/monitor.py"
REMOTE_MONITOR_SCRIPT_PATH = "~/monitor.py"