# Generated by Django 5.1.1 on 2024-09-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0003_host_environment"),
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorhost",
            name="notification_info",
            field=models.CharField(
                blank=True, default=None, max_length=500, null=True, verbose_name="通知人"
            ),
        ),
        migrations.AddField(
            model_name="monitorhost",
            name="notification_type",
            field=models.SmallIntegerField(
                choices=[(0, "邮件通知"), (1, "短信通知"), (2, "微信通知"), (3, "钉钉通知")],
                default=0,
                verbose_name="通知类型",
            ),
        ),
        migrations.AddField(
            model_name="monitorhost",
            name="param",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="monitor.monitorparams",
                verbose_name="监控参数",
            ),
        ),
        migrations.AddField(
            model_name="monitorhost",
            name="value",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="预警阈值"
            ),
        ),
        migrations.AlterField(
            model_name="monitorhost",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="host.host",
                verbose_name="主机",
            ),
        ),
    ]
